name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      ELIXIR_VERSION: "1.18"
      OTP_VERSION: "27"
      MIX_ENV: test
      CI: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}
      - name: Restore Mix/Hex/Rebar cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            deps
            _build
            ~/.mix
            ~/.hex
            ~/.cache/rebar3
          key: ${{ runner.os }}-beam-${{ env.OTP_VERSION }}-ex${{ env.ELIXIR_VERSION }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-beam-${{ env.OTP_VERSION }}-ex${{ env.ELIXIR_VERSION }}-mix-
            ${{ runner.os }}-beam-${{ env.OTP_VERSION }}-ex${{ env.ELIXIR_VERSION }}-
            ${{ runner.os }}-beam-
      - run: mix deps.get
      - run: mix hex.audit
      - run: mix deps.compile
      - run: mix coveralls.json
      - uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover/excoveralls.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ !cancelled() }}
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: coverage/junit-coverage.xml
